#include <stdlib.h>
#include <time.h>
#include "main.h"
#include "defs.h"
#include "utils.h"
void initializeItem();
int checkitemFunctionOne();
void itemFunctionOne();
int checkitemFunctionTwo();
void itemFunctionTwo();
int checkitemFunctionThree();
void itemFunctionThree();
void initializeItem();
